step5(DB接続設定)とstep6(タスクモデル作成)のレビュー
KoosukeAbe/training pull request #2
Opened 2021-06-22 02:13 UTC by KoosukeAbe

レビューよろしくお願い致します

step5 
  - Gemfileにmysql2を追加
  - database.ymlの変更
  
step6
  - DBのモデルクラス作成
  - マイグレーションの追加

2021-06-23 02:40 UTC, UYO123 commented
taskkunフォルダ内に今回記述した文のREADMEは移しちゃってください。
一番上のREADMEは編集前のそのままで置いておいてください。

2021-06-23 03:00 UTC, UYO123 requested changes
test配下は今回Rspecを使用するので削除してしまってください。

2021-06-23 03:00 UTC, UYO123 commented on taskkun/db/migrate/20210622011026_create_tasks.rb
> +      t.boolean :is_deleted, :null => false, :default => 'true'
こちらは削除フラグだと思うのですが default は true ではなく false ではないですか？
また、削除フラグという存在に関しては色々話があるので調べてみると面白いかもしれません。

2021-06-23 07:52 UTC, KoosukeAbe commented on taskkun/db/migrate/20210622011026_create_tasks.rb
> +      t.boolean :is_deleted, :null => false, :default => 'true'
レビューありがとうございます。
RailsのCRUDを使うと今作成してる削除フラグは使えないですね。
調べてみると論理削除が今回のケースに合うことがわかりました。
paranoiaを使うと出来そうなのでpart7のプルリクの方でやってみたいと思います。
また、test配下のファイル削除もテストの際（part7のプルリク）で行いましたのでそちらで確認していただけたらと思います！

論理削除について
https://techblog.kyamanak.com/entry/2017/09/16/192518

2021-06-23 07:53 UTC, KoosukeAbe commented
ReadMeの件、修正しました。
お手数ですが、再度確認よろしくお願い致します。

2021-06-24 00:01 UTC, UYO123 commented
![126079](https://user-images.githubusercontent.com/78333980/123182623-cf387c80-d4ca-11eb-80cb-21e021c7522d.jpeg)

2021-06-24 00:03 UTC, merged